// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v6.31.1
// source: demo/api.proto

package demo

import (
	_ "github.com/danielvladco/go-proto-gql/pkg/graphqlpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// use from common
type ItemIdInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ItemIdInt32) Reset() {
	*x = ItemIdInt32{}
	mi := &file_demo_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemIdInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemIdInt32) ProtoMessage() {}

func (x *ItemIdInt32) ProtoReflect() protoreflect.Message {
	mi := &file_demo_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemIdInt32.ProtoReflect.Descriptor instead.
func (*ItemIdInt32) Descriptor() ([]byte, []int) {
	return file_demo_api_proto_rawDescGZIP(), []int{0}
}

func (x *ItemIdInt32) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_demo_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_demo_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_demo_api_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data  []*Item `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_demo_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_demo_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_demo_api_proto_rawDescGZIP(), []int{2}
}

func (x *Items) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Items) GetData() []*Item {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_demo_api_proto protoreflect.FileDescriptor

var file_demo_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x1a, 0x23, 0x64, 0x61, 0x6e, 0x69, 0x65, 0x6c, 0x76, 0x6c,
	0x61, 0x64, 0x63, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0b, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x06, 0xb2, 0xe0, 0x1f, 0x02, 0x08, 0x01, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x40, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x06, 0xb2, 0xe0, 0x1f, 0x02, 0x08, 0x01, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1c, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x06, 0xb2, 0xe0,
	0x1f, 0x02, 0x08, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x06, 0xb2, 0xe0, 0x1f, 0x02, 0x08, 0x01, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x85, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x6d, 0x6f, 0x12, 0x35, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x11, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x1a, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x0c, 0xb2, 0xe0,
	0x1f, 0x08, 0x08, 0x02, 0x1a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x11, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x1a, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x22, 0x0d, 0xb2, 0xe0, 0x1f, 0x09, 0x08, 0x02, 0x1a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x06, 0xb2, 0xe0, 0x1f, 0x02, 0x1a, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x63, 0x61, 0x73, 0x68,
	0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x6d,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demo_api_proto_rawDescOnce sync.Once
	file_demo_api_proto_rawDescData = file_demo_api_proto_rawDesc
)

func file_demo_api_proto_rawDescGZIP() []byte {
	file_demo_api_proto_rawDescOnce.Do(func() {
		file_demo_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_api_proto_rawDescData)
	})
	return file_demo_api_proto_rawDescData
}

var file_demo_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_demo_api_proto_goTypes = []any{
	(*ItemIdInt32)(nil), // 0: demo.ItemIdInt32
	(*Item)(nil),        // 1: demo.Item
	(*Items)(nil),       // 2: demo.Items
}
var file_demo_api_proto_depIdxs = []int32{
	1, // 0: demo.Items.data:type_name -> demo.Item
	0, // 1: demo.ServiceDemo.GetOne:input_type -> demo.ItemIdInt32
	0, // 2: demo.ServiceDemo.GetMany:input_type -> demo.ItemIdInt32
	1, // 3: demo.ServiceDemo.GetOne:output_type -> demo.Item
	1, // 4: demo.ServiceDemo.GetMany:output_type -> demo.Item
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_demo_api_proto_init() }
func file_demo_api_proto_init() {
	if File_demo_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_api_proto_goTypes,
		DependencyIndexes: file_demo_api_proto_depIdxs,
		MessageInfos:      file_demo_api_proto_msgTypes,
	}.Build()
	File_demo_api_proto = out.File
	file_demo_api_proto_rawDesc = nil
	file_demo_api_proto_goTypes = nil
	file_demo_api_proto_depIdxs = nil
}
