// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: demo/api.proto

package demo

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// use from common
type ItemIdInt32 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter documents by ID
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemIdInt32) Reset() {
	*x = ItemIdInt32{}
	mi := &file_demo_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemIdInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemIdInt32) ProtoMessage() {}

func (x *ItemIdInt32) ProtoReflect() protoreflect.Message {
	mi := &file_demo_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemIdInt32.ProtoReflect.Descriptor instead.
func (*ItemIdInt32) Descriptor() ([]byte, []int) {
	return file_demo_api_proto_rawDescGZIP(), []int{0}
}

func (x *ItemIdInt32) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// item ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// item description
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_demo_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_demo_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_demo_api_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_demo_api_proto protoreflect.FileDescriptor

const file_demo_api_proto_rawDesc = "" +
	"\n" +
	"\x0edemo/api.proto\x12\x04demo\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1d\n" +
	"\vItemIdInt32\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"8\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2M\n" +
	"\vServiceDemo\x12>\n" +
	"\x06GetOne\x12\x11.demo.ItemIdInt32\x1a\n" +
	".demo.Item\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/item/{id}B\x9a\x01\x92As\x12J\n" +
	"\x10Demo Service API\x12/HTTP/JSON API for Demo service via gRPC-Gateway2\x051.0.0*\x01\x012\x10application/json:\x10application/jsonZ\"github.com/becash/apis/gen_go/demob\x06proto3"

var (
	file_demo_api_proto_rawDescOnce sync.Once
	file_demo_api_proto_rawDescData []byte
)

func file_demo_api_proto_rawDescGZIP() []byte {
	file_demo_api_proto_rawDescOnce.Do(func() {
		file_demo_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_api_proto_rawDesc), len(file_demo_api_proto_rawDesc)))
	})
	return file_demo_api_proto_rawDescData
}

var file_demo_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demo_api_proto_goTypes = []any{
	(*ItemIdInt32)(nil), // 0: demo.ItemIdInt32
	(*Item)(nil),        // 1: demo.Item
}
var file_demo_api_proto_depIdxs = []int32{
	0, // 0: demo.ServiceDemo.GetOne:input_type -> demo.ItemIdInt32
	1, // 1: demo.ServiceDemo.GetOne:output_type -> demo.Item
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_api_proto_init() }
func file_demo_api_proto_init() {
	if File_demo_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_api_proto_rawDesc), len(file_demo_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_api_proto_goTypes,
		DependencyIndexes: file_demo_api_proto_depIdxs,
		MessageInfos:      file_demo_api_proto_msgTypes,
	}.Build()
	File_demo_api_proto = out.File
	file_demo_api_proto_goTypes = nil
	file_demo_api_proto_depIdxs = nil
}
