// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: demo/api.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceDemo_GetOne_FullMethodName  = "/demo.ServiceDemo/GetOne"
	ServiceDemo_GetMany_FullMethodName = "/demo.ServiceDemo/GetMany"
)

// ServiceDemoClient is the client API for ServiceDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceDemoClient interface {
	GetOne(ctx context.Context, in *ItemIdInt32, opts ...grpc.CallOption) (*Item, error)
	GetMany(ctx context.Context, in *ItemIdInt32, opts ...grpc.CallOption) (*Item, error)
}

type serviceDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceDemoClient(cc grpc.ClientConnInterface) ServiceDemoClient {
	return &serviceDemoClient{cc}
}

func (c *serviceDemoClient) GetOne(ctx context.Context, in *ItemIdInt32, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ServiceDemo_GetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceDemoClient) GetMany(ctx context.Context, in *ItemIdInt32, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, ServiceDemo_GetMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceDemoServer is the server API for ServiceDemo service.
// All implementations must embed UnimplementedServiceDemoServer
// for forward compatibility.
type ServiceDemoServer interface {
	GetOne(context.Context, *ItemIdInt32) (*Item, error)
	GetMany(context.Context, *ItemIdInt32) (*Item, error)
	mustEmbedUnimplementedServiceDemoServer()
}

// UnimplementedServiceDemoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceDemoServer struct{}

func (UnimplementedServiceDemoServer) GetOne(context.Context, *ItemIdInt32) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedServiceDemoServer) GetMany(context.Context, *ItemIdInt32) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMany not implemented")
}
func (UnimplementedServiceDemoServer) mustEmbedUnimplementedServiceDemoServer() {}
func (UnimplementedServiceDemoServer) testEmbeddedByValue()                     {}

// UnsafeServiceDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceDemoServer will
// result in compilation errors.
type UnsafeServiceDemoServer interface {
	mustEmbedUnimplementedServiceDemoServer()
}

func RegisterServiceDemoServer(s grpc.ServiceRegistrar, srv ServiceDemoServer) {
	// If the following call pancis, it indicates UnimplementedServiceDemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceDemo_ServiceDesc, srv)
}

func _ServiceDemo_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemIdInt32)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceDemoServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceDemo_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceDemoServer).GetOne(ctx, req.(*ItemIdInt32))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceDemo_GetMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemIdInt32)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceDemoServer).GetMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceDemo_GetMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceDemoServer).GetMany(ctx, req.(*ItemIdInt32))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceDemo_ServiceDesc is the grpc.ServiceDesc for ServiceDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.ServiceDemo",
	HandlerType: (*ServiceDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _ServiceDemo_GetOne_Handler,
		},
		{
			MethodName: "GetMany",
			Handler:    _ServiceDemo_GetMany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo/api.proto",
}
