// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: swallow_channel_from_service/api.proto

package swallow_channel_from_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceFromSwallow_GetProduct_FullMethodName    = "/swallow_channel_from_service.ServiceFromSwallow/GetProduct"
	ServiceFromSwallow_GetProducts_FullMethodName   = "/swallow_channel_from_service.ServiceFromSwallow/GetProducts"
	ServiceFromSwallow_UpsertProduct_FullMethodName = "/swallow_channel_from_service.ServiceFromSwallow/UpsertProduct"
)

// ServiceFromSwallowClient is the client API for ServiceFromSwallow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceFromSwallowClient interface {
	// Get on product by some field
	GetProduct(ctx context.Context, in *FieldFilter, opts ...grpc.CallOption) (*Product, error)
	GetProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Product, error)
	UpsertProduct(ctx context.Context, in *UpsertProductRequest, opts ...grpc.CallOption) (*Product, error)
}

type serviceFromSwallowClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceFromSwallowClient(cc grpc.ClientConnInterface) ServiceFromSwallowClient {
	return &serviceFromSwallowClient{cc}
}

func (c *serviceFromSwallowClient) GetProduct(ctx context.Context, in *FieldFilter, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ServiceFromSwallow_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceFromSwallowClient) GetProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ServiceFromSwallow_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceFromSwallowClient) UpsertProduct(ctx context.Context, in *UpsertProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ServiceFromSwallow_UpsertProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceFromSwallowServer is the server API for ServiceFromSwallow service.
// All implementations must embed UnimplementedServiceFromSwallowServer
// for forward compatibility.
type ServiceFromSwallowServer interface {
	// Get on product by some field
	GetProduct(context.Context, *FieldFilter) (*Product, error)
	GetProducts(context.Context, *emptypb.Empty) (*Product, error)
	UpsertProduct(context.Context, *UpsertProductRequest) (*Product, error)
	mustEmbedUnimplementedServiceFromSwallowServer()
}

// UnimplementedServiceFromSwallowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceFromSwallowServer struct{}

func (UnimplementedServiceFromSwallowServer) GetProduct(context.Context, *FieldFilter) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedServiceFromSwallowServer) GetProducts(context.Context, *emptypb.Empty) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedServiceFromSwallowServer) UpsertProduct(context.Context, *UpsertProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProduct not implemented")
}
func (UnimplementedServiceFromSwallowServer) mustEmbedUnimplementedServiceFromSwallowServer() {}
func (UnimplementedServiceFromSwallowServer) testEmbeddedByValue()                            {}

// UnsafeServiceFromSwallowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceFromSwallowServer will
// result in compilation errors.
type UnsafeServiceFromSwallowServer interface {
	mustEmbedUnimplementedServiceFromSwallowServer()
}

func RegisterServiceFromSwallowServer(s grpc.ServiceRegistrar, srv ServiceFromSwallowServer) {
	// If the following call pancis, it indicates UnimplementedServiceFromSwallowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceFromSwallow_ServiceDesc, srv)
}

func _ServiceFromSwallow_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FieldFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceFromSwallowServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceFromSwallow_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceFromSwallowServer).GetProduct(ctx, req.(*FieldFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceFromSwallow_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceFromSwallowServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceFromSwallow_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceFromSwallowServer).GetProducts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceFromSwallow_UpsertProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceFromSwallowServer).UpsertProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceFromSwallow_UpsertProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceFromSwallowServer).UpsertProduct(ctx, req.(*UpsertProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceFromSwallow_ServiceDesc is the grpc.ServiceDesc for ServiceFromSwallow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceFromSwallow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swallow_channel_from_service.ServiceFromSwallow",
	HandlerType: (*ServiceFromSwallowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ServiceFromSwallow_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _ServiceFromSwallow_GetProducts_Handler,
		},
		{
			MethodName: "UpsertProduct",
			Handler:    _ServiceFromSwallow_UpsertProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swallow_channel_from_service/api.proto",
}
