// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: swallow_channel_to_service/api.proto

package swallow_channel_to_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceToSwallow_GetProduct_FullMethodName    = "/swallow_channel_to_service.ServiceToSwallow/GetProduct"
	ServiceToSwallow_GetProducts_FullMethodName   = "/swallow_channel_to_service.ServiceToSwallow/GetProducts"
	ServiceToSwallow_UpsertProduct_FullMethodName = "/swallow_channel_to_service.ServiceToSwallow/UpsertProduct"
)

// ServiceToSwallowClient is the client API for ServiceToSwallow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceToSwallowClient interface {
	// Get on product by some field
	GetProduct(ctx context.Context, in *FieldFilter, opts ...grpc.CallOption) (*Product, error)
	GetProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Product, error)
	UpsertProduct(ctx context.Context, in *UpsertProductRequest, opts ...grpc.CallOption) (*Product, error)
}

type serviceToSwallowClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceToSwallowClient(cc grpc.ClientConnInterface) ServiceToSwallowClient {
	return &serviceToSwallowClient{cc}
}

func (c *serviceToSwallowClient) GetProduct(ctx context.Context, in *FieldFilter, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ServiceToSwallow_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceToSwallowClient) GetProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ServiceToSwallow_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceToSwallowClient) UpsertProduct(ctx context.Context, in *UpsertProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, ServiceToSwallow_UpsertProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceToSwallowServer is the server API for ServiceToSwallow service.
// All implementations must embed UnimplementedServiceToSwallowServer
// for forward compatibility.
type ServiceToSwallowServer interface {
	// Get on product by some field
	GetProduct(context.Context, *FieldFilter) (*Product, error)
	GetProducts(context.Context, *emptypb.Empty) (*Product, error)
	UpsertProduct(context.Context, *UpsertProductRequest) (*Product, error)
	mustEmbedUnimplementedServiceToSwallowServer()
}

// UnimplementedServiceToSwallowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceToSwallowServer struct{}

func (UnimplementedServiceToSwallowServer) GetProduct(context.Context, *FieldFilter) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedServiceToSwallowServer) GetProducts(context.Context, *emptypb.Empty) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedServiceToSwallowServer) UpsertProduct(context.Context, *UpsertProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProduct not implemented")
}
func (UnimplementedServiceToSwallowServer) mustEmbedUnimplementedServiceToSwallowServer() {}
func (UnimplementedServiceToSwallowServer) testEmbeddedByValue()                          {}

// UnsafeServiceToSwallowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceToSwallowServer will
// result in compilation errors.
type UnsafeServiceToSwallowServer interface {
	mustEmbedUnimplementedServiceToSwallowServer()
}

func RegisterServiceToSwallowServer(s grpc.ServiceRegistrar, srv ServiceToSwallowServer) {
	// If the following call pancis, it indicates UnimplementedServiceToSwallowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceToSwallow_ServiceDesc, srv)
}

func _ServiceToSwallow_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FieldFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceToSwallowServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceToSwallow_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceToSwallowServer).GetProduct(ctx, req.(*FieldFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceToSwallow_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceToSwallowServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceToSwallow_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceToSwallowServer).GetProducts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceToSwallow_UpsertProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceToSwallowServer).UpsertProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceToSwallow_UpsertProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceToSwallowServer).UpsertProduct(ctx, req.(*UpsertProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceToSwallow_ServiceDesc is the grpc.ServiceDesc for ServiceToSwallow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceToSwallow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swallow_channel_to_service.ServiceToSwallow",
	HandlerType: (*ServiceToSwallowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ServiceToSwallow_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _ServiceToSwallow_GetProducts_Handler,
		},
		{
			MethodName: "UpsertProduct",
			Handler:    _ServiceToSwallow_UpsertProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swallow_channel_to_service/api.proto",
}
