// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: swallow_channel_to_service/messages.proto

package swallow_channel_to_service

import (
	common "github.com/becash/apis/gen_go/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductAvailabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Range         *common.DateRange      `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAvailabilitiesRequest) Reset() {
	*x = ProductAvailabilitiesRequest{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAvailabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAvailabilitiesRequest) ProtoMessage() {}

func (x *ProductAvailabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAvailabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ProductAvailabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ProductAvailabilitiesRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductAvailabilitiesRequest) GetRange() *common.DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type Availability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Currency      common.Currency        `protobuf:"varint,3,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Availability) Reset() {
	*x = Availability{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Availability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Availability) ProtoMessage() {}

func (x *Availability) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Availability.ProtoReflect.Descriptor instead.
func (*Availability) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Availability) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Availability) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Availability) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

type Availabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Availability          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Availabilities) Reset() {
	*x = Availabilities{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Availabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Availabilities) ProtoMessage() {}

func (x *Availabilities) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Availabilities.ProtoReflect.Descriptor instead.
func (*Availabilities) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Availabilities) GetData() *Availability {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Availabilities) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Products struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Product             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Products) Reset() {
	*x = Products{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Products) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Products) ProtoMessage() {}

func (x *Products) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Products.ProtoReflect.Descriptor instead.
func (*Products) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Products) GetData() []*Product {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Products) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    common.Suppliers       `protobuf:"varint,1,opt,name=supplier_id,json=supplierId,proto3,enum=common.Suppliers" json:"supplier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsRequest) Reset() {
	*x = ProductsRequest{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsRequest) ProtoMessage() {}

func (x *ProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsRequest.ProtoReflect.Descriptor instead.
func (*ProductsRequest) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ProductsRequest) GetSupplierId() common.Suppliers {
	if x != nil {
		return x.SupplierId
	}
	return common.Suppliers(0)
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId    common.Suppliers       `protobuf:"varint,2,opt,name=supplier_id,json=supplierId,proto3,enum=common.Suppliers" json:"supplier_id,omitempty"`
	Title         *common.I18N           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *common.I18N           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetSupplierId() common.Suppliers {
	if x != nil {
		return x.SupplierId
	}
	return common.Suppliers(0)
}

func (x *Product) GetTitle() *common.I18N {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Product) GetDescription() *common.I18N {
	if x != nil {
		return x.Description
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      common.Currency        `protobuf:"varint,3,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRequest) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Currency      common.Currency        `protobuf:"varint,3,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	Status        common.OrderStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=common.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Order) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

func (x *Order) GetStatus() common.OrderStatus {
	if x != nil {
		return x.Status
	}
	return common.OrderStatus(0)
}

type Orders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Order               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Orders) GetData() []*Order {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Orders) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *common.DateRange      `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersRequest) Reset() {
	*x = OrdersRequest{}
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersRequest) ProtoMessage() {}

func (x *OrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swallow_channel_to_service_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersRequest.ProtoReflect.Descriptor instead.
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return file_swallow_channel_to_service_messages_proto_rawDescGZIP(), []int{9}
}

func (x *OrdersRequest) GetRange() *common.DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

var File_swallow_channel_to_service_messages_proto protoreflect.FileDescriptor

const file_swallow_channel_to_service_messages_proto_rawDesc = "" +
	"\n" +
	")swallow_channel_to_service/messages.proto\x12\x1aswallow_channel_to_service\x1a\x12common/enums.proto\x1a\x11common/i18n.proto\x1a\x12common/range.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"f\n" +
	"\x1cProductAvailabilitiesRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12'\n" +
	"\x05range\x18\x02 \x01(\v2\x11.common.DateRangeR\x05range\"\x94\x01\n" +
	"\fAvailability\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12,\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x10.common.CurrencyR\bcurrency\"d\n" +
	"\x0eAvailabilities\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.swallow_channel_to_service.AvailabilityR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"Y\n" +
	"\bProducts\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.swallow_channel_to_service.ProductR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"E\n" +
	"\x0fProductsRequest\x122\n" +
	"\vsupplier_id\x18\x01 \x01(\x0e2\x11.common.SuppliersR\n" +
	"supplierId\"\xa1\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x122\n" +
	"\vsupplier_id\x18\x02 \x01(\x0e2\x11.common.SuppliersR\n" +
	"supplierId\x12\"\n" +
	"\x05title\x18\x03 \x01(\v2\f.common.I18nR\x05title\x12.\n" +
	"\vdescription\x18\x04 \x01(\v2\f.common.I18nR\vdescription\"B\n" +
	"\x12CreateOrderRequest\x12,\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x10.common.CurrencyR\bcurrency\"\xa8\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12,\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x10.common.CurrencyR\bcurrency\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.common.OrderStatusR\x06status\"U\n" +
	"\x06Orders\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.swallow_channel_to_service.OrderR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\rOrdersRequest\x12'\n" +
	"\x05range\x18\x02 \x01(\v2\x11.common.DateRangeR\x05rangeB\xf4\x01\x92A\xb6\x01\x12\x8c\x01\n" +
	"bSwallow Service API Channel, Direction from External source ( is client ) to US service ( server )\x12!HTTP/JSON API for Swallow service2\x030.1*\x01\x012\x10application/json:\x10application/jsonZ8github.com/becash/apis/gen_go/swallow_channel_to_serviceb\x06proto3"

var (
	file_swallow_channel_to_service_messages_proto_rawDescOnce sync.Once
	file_swallow_channel_to_service_messages_proto_rawDescData []byte
)

func file_swallow_channel_to_service_messages_proto_rawDescGZIP() []byte {
	file_swallow_channel_to_service_messages_proto_rawDescOnce.Do(func() {
		file_swallow_channel_to_service_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swallow_channel_to_service_messages_proto_rawDesc), len(file_swallow_channel_to_service_messages_proto_rawDesc)))
	})
	return file_swallow_channel_to_service_messages_proto_rawDescData
}

var file_swallow_channel_to_service_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_swallow_channel_to_service_messages_proto_goTypes = []any{
	(*ProductAvailabilitiesRequest)(nil), // 0: swallow_channel_to_service.ProductAvailabilitiesRequest
	(*Availability)(nil),                 // 1: swallow_channel_to_service.Availability
	(*Availabilities)(nil),               // 2: swallow_channel_to_service.Availabilities
	(*Products)(nil),                     // 3: swallow_channel_to_service.Products
	(*ProductsRequest)(nil),              // 4: swallow_channel_to_service.ProductsRequest
	(*Product)(nil),                      // 5: swallow_channel_to_service.Product
	(*CreateOrderRequest)(nil),           // 6: swallow_channel_to_service.CreateOrderRequest
	(*Order)(nil),                        // 7: swallow_channel_to_service.Order
	(*Orders)(nil),                       // 8: swallow_channel_to_service.Orders
	(*OrdersRequest)(nil),                // 9: swallow_channel_to_service.OrdersRequest
	(*common.DateRange)(nil),             // 10: common.DateRange
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
	(common.Currency)(0),                 // 12: common.Currency
	(common.Suppliers)(0),                // 13: common.Suppliers
	(*common.I18N)(nil),                  // 14: common.I18n
	(common.OrderStatus)(0),              // 15: common.OrderStatus
}
var file_swallow_channel_to_service_messages_proto_depIdxs = []int32{
	10, // 0: swallow_channel_to_service.ProductAvailabilitiesRequest.range:type_name -> common.DateRange
	11, // 1: swallow_channel_to_service.Availability.date_time:type_name -> google.protobuf.Timestamp
	12, // 2: swallow_channel_to_service.Availability.currency:type_name -> common.Currency
	1,  // 3: swallow_channel_to_service.Availabilities.data:type_name -> swallow_channel_to_service.Availability
	5,  // 4: swallow_channel_to_service.Products.data:type_name -> swallow_channel_to_service.Product
	13, // 5: swallow_channel_to_service.ProductsRequest.supplier_id:type_name -> common.Suppliers
	13, // 6: swallow_channel_to_service.Product.supplier_id:type_name -> common.Suppliers
	14, // 7: swallow_channel_to_service.Product.title:type_name -> common.I18n
	14, // 8: swallow_channel_to_service.Product.description:type_name -> common.I18n
	12, // 9: swallow_channel_to_service.CreateOrderRequest.currency:type_name -> common.Currency
	11, // 10: swallow_channel_to_service.Order.created:type_name -> google.protobuf.Timestamp
	12, // 11: swallow_channel_to_service.Order.currency:type_name -> common.Currency
	15, // 12: swallow_channel_to_service.Order.status:type_name -> common.OrderStatus
	7,  // 13: swallow_channel_to_service.Orders.data:type_name -> swallow_channel_to_service.Order
	10, // 14: swallow_channel_to_service.OrdersRequest.range:type_name -> common.DateRange
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_swallow_channel_to_service_messages_proto_init() }
func file_swallow_channel_to_service_messages_proto_init() {
	if File_swallow_channel_to_service_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swallow_channel_to_service_messages_proto_rawDesc), len(file_swallow_channel_to_service_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swallow_channel_to_service_messages_proto_goTypes,
		DependencyIndexes: file_swallow_channel_to_service_messages_proto_depIdxs,
		MessageInfos:      file_swallow_channel_to_service_messages_proto_msgTypes,
	}.Build()
	File_swallow_channel_to_service_messages_proto = out.File
	file_swallow_channel_to_service_messages_proto_goTypes = nil
	file_swallow_channel_to_service_messages_proto_depIdxs = nil
}
