syntax = "proto3";

package common;

option go_package = "github.com/becash/apis/gen_go/common";

enum Suppliers {
  SUPPLIER_UNSPECIFIED = 0;
  YANOJA = 1;
}

enum CustomerCategories {
  CC_UNSPECIFIED = 0;
  ADULT = 1;
  CHILD = 2;
}

enum Currency {
  CURRENCY_UNSPECIFIED = 0;
  MDL = 1;
  USD = 2;
  EUR = 3;
}

enum OrderStatus {
  OS_UNSPECIFIED = 0;
  //Mean that order is not confirmed by customer, like prebooking or reservation of somthing
  DRAFT = 1;
}

enum ProductType {
  PT_UNSPECIFIED = 0;
  //is a physical product
  GOOD = 1;
  SERVICE = 2;
}
