// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: common/enums.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suppliers int32

const (
	Suppliers_SUPPLIER_UNSPECIFIED Suppliers = 0
	Suppliers_YANOJA               Suppliers = 1
)

// Enum value maps for Suppliers.
var (
	Suppliers_name = map[int32]string{
		0: "SUPPLIER_UNSPECIFIED",
		1: "YANOJA",
	}
	Suppliers_value = map[string]int32{
		"SUPPLIER_UNSPECIFIED": 0,
		"YANOJA":               1,
	}
)

func (x Suppliers) Enum() *Suppliers {
	p := new(Suppliers)
	*p = x
	return p
}

func (x Suppliers) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suppliers) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enums_proto_enumTypes[0].Descriptor()
}

func (Suppliers) Type() protoreflect.EnumType {
	return &file_common_enums_proto_enumTypes[0]
}

func (x Suppliers) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suppliers.Descriptor instead.
func (Suppliers) EnumDescriptor() ([]byte, []int) {
	return file_common_enums_proto_rawDescGZIP(), []int{0}
}

type CustomerCategories int32

const (
	CustomerCategories_CC_UNSPECIFIED CustomerCategories = 0
	CustomerCategories_ADULT          CustomerCategories = 1
	CustomerCategories_CHILD          CustomerCategories = 2
)

// Enum value maps for CustomerCategories.
var (
	CustomerCategories_name = map[int32]string{
		0: "CC_UNSPECIFIED",
		1: "ADULT",
		2: "CHILD",
	}
	CustomerCategories_value = map[string]int32{
		"CC_UNSPECIFIED": 0,
		"ADULT":          1,
		"CHILD":          2,
	}
)

func (x CustomerCategories) Enum() *CustomerCategories {
	p := new(CustomerCategories)
	*p = x
	return p
}

func (x CustomerCategories) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerCategories) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enums_proto_enumTypes[1].Descriptor()
}

func (CustomerCategories) Type() protoreflect.EnumType {
	return &file_common_enums_proto_enumTypes[1]
}

func (x CustomerCategories) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerCategories.Descriptor instead.
func (CustomerCategories) EnumDescriptor() ([]byte, []int) {
	return file_common_enums_proto_rawDescGZIP(), []int{1}
}

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_MDL                  Currency = 1
	Currency_USD                  Currency = 2
	Currency_EUR                  Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "MDL",
		2: "USD",
		3: "EUR",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"MDL":                  1,
		"USD":                  2,
		"EUR":                  3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enums_proto_enumTypes[2].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_common_enums_proto_enumTypes[2]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_common_enums_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	OrderStatus_OS_UNSPECIFIED OrderStatus = 0
	// Mean that order is not confirmed by customer, like prebooking or reservation of somthing
	OrderStatus_DRAFT OrderStatus = 1
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "OS_UNSPECIFIED",
		1: "DRAFT",
	}
	OrderStatus_value = map[string]int32{
		"OS_UNSPECIFIED": 0,
		"DRAFT":          1,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enums_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_common_enums_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enums_proto_rawDescGZIP(), []int{3}
}

var File_common_enums_proto protoreflect.FileDescriptor

const file_common_enums_proto_rawDesc = "" +
	"\n" +
	"\x12common/enums.proto\x12\x06common*1\n" +
	"\tSuppliers\x12\x18\n" +
	"\x14SUPPLIER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06YANOJA\x10\x01*>\n" +
	"\x12CustomerCategories\x12\x12\n" +
	"\x0eCC_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADULT\x10\x01\x12\t\n" +
	"\x05CHILD\x10\x02*?\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03MDL\x10\x01\x12\a\n" +
	"\x03USD\x10\x02\x12\a\n" +
	"\x03EUR\x10\x03*,\n" +
	"\vOrderStatus\x12\x12\n" +
	"\x0eOS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01B&Z$github.com/becash/apis/gen_go/commonb\x06proto3"

var (
	file_common_enums_proto_rawDescOnce sync.Once
	file_common_enums_proto_rawDescData []byte
)

func file_common_enums_proto_rawDescGZIP() []byte {
	file_common_enums_proto_rawDescOnce.Do(func() {
		file_common_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_enums_proto_rawDesc), len(file_common_enums_proto_rawDesc)))
	})
	return file_common_enums_proto_rawDescData
}

var file_common_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_enums_proto_goTypes = []any{
	(Suppliers)(0),          // 0: common.Suppliers
	(CustomerCategories)(0), // 1: common.CustomerCategories
	(Currency)(0),           // 2: common.Currency
	(OrderStatus)(0),        // 3: common.OrderStatus
}
var file_common_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_enums_proto_init() }
func file_common_enums_proto_init() {
	if File_common_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_enums_proto_rawDesc), len(file_common_enums_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_enums_proto_goTypes,
		DependencyIndexes: file_common_enums_proto_depIdxs,
		EnumInfos:         file_common_enums_proto_enumTypes,
	}.Build()
	File_common_enums_proto = out.File
	file_common_enums_proto_goTypes = nil
	file_common_enums_proto_depIdxs = nil
}
