// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: common/i18n.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locale int32

const (
	Locale_LOCALE_UNSPECIFIED Locale = 0
	Locale_EN_US              Locale = 1
)

// Enum value maps for Locale.
var (
	Locale_name = map[int32]string{
		0: "LOCALE_UNSPECIFIED",
		1: "EN_US",
	}
	Locale_value = map[string]int32{
		"LOCALE_UNSPECIFIED": 0,
		"EN_US":              1,
	}
)

func (x Locale) Enum() *Locale {
	p := new(Locale)
	*p = x
	return p
}

func (x Locale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Locale) Descriptor() protoreflect.EnumDescriptor {
	return file_common_i18n_proto_enumTypes[0].Descriptor()
}

func (Locale) Type() protoreflect.EnumType {
	return &file_common_i18n_proto_enumTypes[0]
}

func (x Locale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Locale.Descriptor instead.
func (Locale) EnumDescriptor() ([]byte, []int) {
	return file_common_i18n_proto_rawDescGZIP(), []int{0}
}

type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0
	Language_EN                   Language = 1
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "EN",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"EN":                   1,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_common_i18n_proto_enumTypes[1].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_common_i18n_proto_enumTypes[1]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_common_i18n_proto_rawDescGZIP(), []int{1}
}

type I18N struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	En            string                 `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I18N) Reset() {
	*x = I18N{}
	mi := &file_common_i18n_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I18N) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18N) ProtoMessage() {}

func (x *I18N) ProtoReflect() protoreflect.Message {
	mi := &file_common_i18n_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18N.ProtoReflect.Descriptor instead.
func (*I18N) Descriptor() ([]byte, []int) {
	return file_common_i18n_proto_rawDescGZIP(), []int{0}
}

func (x *I18N) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

var File_common_i18n_proto protoreflect.FileDescriptor

const file_common_i18n_proto_rawDesc = "" +
	"\n" +
	"\x11common/i18n.proto\x12\x06common\"\x16\n" +
	"\x04I18n\x12\x0e\n" +
	"\x02en\x18\x01 \x01(\tR\x02en*+\n" +
	"\x06Locale\x12\x16\n" +
	"\x12LOCALE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EN_US\x10\x01*,\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02EN\x10\x01B&Z$github.com/becash/apis/gen_go/commonb\x06proto3"

var (
	file_common_i18n_proto_rawDescOnce sync.Once
	file_common_i18n_proto_rawDescData []byte
)

func file_common_i18n_proto_rawDescGZIP() []byte {
	file_common_i18n_proto_rawDescOnce.Do(func() {
		file_common_i18n_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_i18n_proto_rawDesc), len(file_common_i18n_proto_rawDesc)))
	})
	return file_common_i18n_proto_rawDescData
}

var file_common_i18n_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_i18n_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_i18n_proto_goTypes = []any{
	(Locale)(0),   // 0: common.Locale
	(Language)(0), // 1: common.Language
	(*I18N)(nil),  // 2: common.I18n
}
var file_common_i18n_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_i18n_proto_init() }
func file_common_i18n_proto_init() {
	if File_common_i18n_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_i18n_proto_rawDesc), len(file_common_i18n_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_i18n_proto_goTypes,
		DependencyIndexes: file_common_i18n_proto_depIdxs,
		EnumInfos:         file_common_i18n_proto_enumTypes,
		MessageInfos:      file_common_i18n_proto_msgTypes,
	}.Build()
	File_common_i18n_proto = out.File
	file_common_i18n_proto_goTypes = nil
	file_common_i18n_proto_depIdxs = nil
}
