// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: common/suppliers.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suppliers int32

const (
	Suppliers_SUPLIER_UNSPECIFIED Suppliers = 0
	Suppliers_YANOJA              Suppliers = 1
)

// Enum value maps for Suppliers.
var (
	Suppliers_name = map[int32]string{
		0: "SUPLIER_UNSPECIFIED",
		1: "YANOJA",
	}
	Suppliers_value = map[string]int32{
		"SUPLIER_UNSPECIFIED": 0,
		"YANOJA":              1,
	}
)

func (x Suppliers) Enum() *Suppliers {
	p := new(Suppliers)
	*p = x
	return p
}

func (x Suppliers) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suppliers) Descriptor() protoreflect.EnumDescriptor {
	return file_common_suppliers_proto_enumTypes[0].Descriptor()
}

func (Suppliers) Type() protoreflect.EnumType {
	return &file_common_suppliers_proto_enumTypes[0]
}

func (x Suppliers) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suppliers.Descriptor instead.
func (Suppliers) EnumDescriptor() ([]byte, []int) {
	return file_common_suppliers_proto_rawDescGZIP(), []int{0}
}

var File_common_suppliers_proto protoreflect.FileDescriptor

const file_common_suppliers_proto_rawDesc = "" +
	"\n" +
	"\x16common/suppliers.proto\x12\x06common*0\n" +
	"\tSuppliers\x12\x17\n" +
	"\x13SUPLIER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06YANOJA\x10\x01B&Z$github.com/becash/apis/gen_go/commonb\x06proto3"

var (
	file_common_suppliers_proto_rawDescOnce sync.Once
	file_common_suppliers_proto_rawDescData []byte
)

func file_common_suppliers_proto_rawDescGZIP() []byte {
	file_common_suppliers_proto_rawDescOnce.Do(func() {
		file_common_suppliers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_suppliers_proto_rawDesc), len(file_common_suppliers_proto_rawDesc)))
	})
	return file_common_suppliers_proto_rawDescData
}

var file_common_suppliers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_suppliers_proto_goTypes = []any{
	(Suppliers)(0), // 0: common.Suppliers
}
var file_common_suppliers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_suppliers_proto_init() }
func file_common_suppliers_proto_init() {
	if File_common_suppliers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_suppliers_proto_rawDesc), len(file_common_suppliers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_suppliers_proto_goTypes,
		DependencyIndexes: file_common_suppliers_proto_depIdxs,
		EnumInfos:         file_common_suppliers_proto_enumTypes,
	}.Build()
	File_common_suppliers_proto = out.File
	file_common_suppliers_proto_goTypes = nil
	file_common_suppliers_proto_depIdxs = nil
}
