// Package swallow_channel_to_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package swallow_channel_to_service

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// SwallowChannelFromServiceProduct Can be Ticket/Reservation
type SwallowChannelFromServiceProduct struct {
	// Id item ID
	Id *int32 `json:"id,omitempty"`

	// JsonMetadata client side, data, now we not using them,
	//  but in future if field will participate to internal logic need to be added to Product fields
	JsonMetadata *string `json:"jsonMetadata,omitempty"`
}

// SwallowChannelToServiceAvailabilities defines model for swallow_channel_to_service.Availabilities.
type SwallowChannelToServiceAvailabilities struct {
	Count *string                              `json:"count,omitempty"`
	Data  *SwallowChannelToServiceAvailability `json:"data,omitempty"`
}

// SwallowChannelToServiceAvailability defines model for swallow_channel_to_service.Availability.
type SwallowChannelToServiceAvailability struct {
	Currency  *int       `json:"currency,omitempty"`
	DateTime  *time.Time `json:"dateTime,omitempty"`
	ProductId *int32     `json:"productId,omitempty"`
}

// ServiceFromSwallowUpsertProductParams defines parameters for ServiceFromSwallowUpsertProduct.
type ServiceFromSwallowUpsertProductParams struct {
	// Id item ID, if filed exist: Update else Create
	Id *int32 `form:"id,omitempty" json:"id,omitempty"`

	// JsonMetadata client side, data, now we not using them,
	//  but in future if field will participate to internal logic need to be added to Product fields
	JsonMetadata *string `form:"jsonMetadata,omitempty" json:"jsonMetadata,omitempty"`
}

// ServiceToSwallowGetAvailabilityOfProductParams defines parameters for ServiceToSwallowGetAvailabilityOfProduct.
type ServiceToSwallowGetAvailabilityOfProductParams struct {
	RangeGte *time.Time `form:"range.gte,omitempty" json:"range.gte,omitempty"`
	RangeLte *time.Time `form:"range.lte,omitempty" json:"range.lte,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/product)
	ServiceFromSwallowUpsertProduct(c *gin.Context, params ServiceFromSwallowUpsertProductParams)

	// (GET /v1/product-availabilities/{productId})
	ServiceToSwallowGetAvailabilityOfProduct(c *gin.Context, productId int32, params ServiceToSwallowGetAvailabilityOfProductParams)

	// (GET /v1/product/{id})
	ServiceFromSwallowGetProduct(c *gin.Context, id int32)

	// (GET /v1/products)
	ServiceFromSwallowGetProducts(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ServiceFromSwallowUpsertProduct operation middleware
func (siw *ServerInterfaceWrapper) ServiceFromSwallowUpsertProduct(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceFromSwallowUpsertProductParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "jsonMetadata" -------------

	err = runtime.BindQueryParameter("form", true, false, "jsonMetadata", c.Request.URL.Query(), &params.JsonMetadata)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter jsonMetadata: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceFromSwallowUpsertProduct(c, params)
}

// ServiceToSwallowGetAvailabilityOfProduct operation middleware
func (siw *ServerInterfaceWrapper) ServiceToSwallowGetAvailabilityOfProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId int32

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceToSwallowGetAvailabilityOfProductParams

	// ------------- Optional query parameter "range.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "range.gte", c.Request.URL.Query(), &params.RangeGte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter range.gte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "range.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "range.lte", c.Request.URL.Query(), &params.RangeLte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter range.lte: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceToSwallowGetAvailabilityOfProduct(c, productId, params)
}

// ServiceFromSwallowGetProduct operation middleware
func (siw *ServerInterfaceWrapper) ServiceFromSwallowGetProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceFromSwallowGetProduct(c, id)
}

// ServiceFromSwallowGetProducts operation middleware
func (siw *ServerInterfaceWrapper) ServiceFromSwallowGetProducts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceFromSwallowGetProducts(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/product", wrapper.ServiceFromSwallowUpsertProduct)
	router.GET(options.BaseURL+"/v1/product-availabilities/:productId", wrapper.ServiceToSwallowGetAvailabilityOfProduct)
	router.GET(options.BaseURL+"/v1/product/:id", wrapper.ServiceFromSwallowGetProduct)
	router.GET(options.BaseURL+"/v1/products", wrapper.ServiceFromSwallowGetProducts)
}
