// Package swallow_channel_to_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package swallow_channel_to_service

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CommonI18n defines model for common.I18n.
type CommonI18n struct {
	En *string `json:"en,omitempty"`
}

// SwallowChannelToServiceAvailabilities defines model for swallow_channel_to_service.Availabilities.
type SwallowChannelToServiceAvailabilities struct {
	Count *string                              `json:"count,omitempty"`
	Data  *SwallowChannelToServiceAvailability `json:"data,omitempty"`
}

// SwallowChannelToServiceAvailability defines model for swallow_channel_to_service.Availability.
type SwallowChannelToServiceAvailability struct {
	Currency  *int       `json:"currency,omitempty"`
	DateTime  *time.Time `json:"dateTime,omitempty"`
	ProductId *int32     `json:"productId,omitempty"`
}

// SwallowChannelToServiceProduct defines model for swallow_channel_to_service.Product.
type SwallowChannelToServiceProduct struct {
	Description *CommonI18n `json:"description,omitempty"`
	Id          *int32      `json:"id,omitempty"`
	SupplierId  *int        `json:"supplierId,omitempty"`
	Title       *CommonI18n `json:"title,omitempty"`
}

// SwallowChannelToServiceProducts defines model for swallow_channel_to_service.Products.
type SwallowChannelToServiceProducts struct {
	Count *string                         `json:"count,omitempty"`
	Data  *SwallowChannelToServiceProduct `json:"data,omitempty"`
}

// ServiceToSwallowGetAvailabilityOfProductParams defines parameters for ServiceToSwallowGetAvailabilityOfProduct.
type ServiceToSwallowGetAvailabilityOfProductParams struct {
	RangeGte *time.Time `form:"range.gte,omitempty" json:"range.gte,omitempty"`
	RangeLte *time.Time `form:"range.lte,omitempty" json:"range.lte,omitempty"`
}

// ServiceToSwallowGetProductsParams defines parameters for ServiceToSwallowGetProducts.
type ServiceToSwallowGetProductsParams struct {
	SupplierId *int `form:"supplierId,omitempty" json:"supplierId,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /product-availabilities/{productId})
	ServiceToSwallowGetAvailabilityOfProduct(c *gin.Context, productId int32, params ServiceToSwallowGetAvailabilityOfProductParams)

	// (GET /product/{id})
	ServiceToSwallowGetProduct(c *gin.Context, id int32)

	// (GET /products/)
	ServiceToSwallowGetProducts(c *gin.Context, params ServiceToSwallowGetProductsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ServiceToSwallowGetAvailabilityOfProduct operation middleware
func (siw *ServerInterfaceWrapper) ServiceToSwallowGetAvailabilityOfProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId int32

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceToSwallowGetAvailabilityOfProductParams

	// ------------- Optional query parameter "range.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "range.gte", c.Request.URL.Query(), &params.RangeGte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter range.gte: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "range.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "range.lte", c.Request.URL.Query(), &params.RangeLte)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter range.lte: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceToSwallowGetAvailabilityOfProduct(c, productId, params)
}

// ServiceToSwallowGetProduct operation middleware
func (siw *ServerInterfaceWrapper) ServiceToSwallowGetProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceToSwallowGetProduct(c, id)
}

// ServiceToSwallowGetProducts operation middleware
func (siw *ServerInterfaceWrapper) ServiceToSwallowGetProducts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceToSwallowGetProductsParams

	// ------------- Optional query parameter "supplierId" -------------

	err = runtime.BindQueryParameter("form", true, false, "supplierId", c.Request.URL.Query(), &params.SupplierId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ServiceToSwallowGetProducts(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/product-availabilities/:productId", wrapper.ServiceToSwallowGetAvailabilityOfProduct)
	router.GET(options.BaseURL+"/product/:id", wrapper.ServiceToSwallowGetProduct)
	router.GET(options.BaseURL+"/products/", wrapper.ServiceToSwallowGetProducts)
}
