// Package swallow_channel_from_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package swallow_channel_from_service

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// SwallowChannelToServiceProduct Can be Ticket/Reservation
type SwallowChannelToServiceProduct struct {
	// Id item ID
	Id *int32 `json:"id,omitempty"`

	// JsonMetadata client side, data, now we not using them,
	//  but in future if field will participate to internal logic need to be added to Product fields
	JsonMetadata *string `json:"jsonMetadata,omitempty"`
}

// ServiceToSwallowUpsertProductParams defines parameters for ServiceToSwallowUpsertProduct.
type ServiceToSwallowUpsertProductParams struct {
	// Id item ID, if filed exist: Update else Create
	Id *int32 `form:"id,omitempty" json:"id,omitempty"`

	// JsonMetadata client side, data, now we not using them,
	//  but in future if field will participate to internal logic need to be added to Product fields
	JsonMetadata *string `form:"jsonMetadata,omitempty" json:"jsonMetadata,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ServiceToSwallowUpsertProduct request
	ServiceToSwallowUpsertProduct(ctx context.Context, params *ServiceToSwallowUpsertProductParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ServiceToSwallowGetProduct request
	ServiceToSwallowGetProduct(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ServiceToSwallowGetProducts request
	ServiceToSwallowGetProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ServiceToSwallowUpsertProduct(ctx context.Context, params *ServiceToSwallowUpsertProductParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewServiceToSwallowUpsertProductRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ServiceToSwallowGetProduct(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewServiceToSwallowGetProductRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ServiceToSwallowGetProducts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewServiceToSwallowGetProductsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewServiceToSwallowUpsertProductRequest generates requests for ServiceToSwallowUpsertProduct
func NewServiceToSwallowUpsertProductRequest(server string, params *ServiceToSwallowUpsertProductParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/product")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "id", runtime.ParamLocationQuery, *params.Id); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.JsonMetadata != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "jsonMetadata", runtime.ParamLocationQuery, *params.JsonMetadata); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewServiceToSwallowGetProductRequest generates requests for ServiceToSwallowGetProduct
func NewServiceToSwallowGetProductRequest(server string, id int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/product/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewServiceToSwallowGetProductsRequest generates requests for ServiceToSwallowGetProducts
func NewServiceToSwallowGetProductsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ServiceToSwallowUpsertProductWithResponse request
	ServiceToSwallowUpsertProductWithResponse(ctx context.Context, params *ServiceToSwallowUpsertProductParams, reqEditors ...RequestEditorFn) (*ServiceToSwallowUpsertProductResponse, error)

	// ServiceToSwallowGetProductWithResponse request
	ServiceToSwallowGetProductWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*ServiceToSwallowGetProductResponse, error)

	// ServiceToSwallowGetProductsWithResponse request
	ServiceToSwallowGetProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ServiceToSwallowGetProductsResponse, error)
}

type ServiceToSwallowUpsertProductResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SwallowChannelToServiceProduct
}

// Status returns HTTPResponse.Status
func (r ServiceToSwallowUpsertProductResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ServiceToSwallowUpsertProductResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ServiceToSwallowGetProductResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SwallowChannelToServiceProduct
}

// Status returns HTTPResponse.Status
func (r ServiceToSwallowGetProductResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ServiceToSwallowGetProductResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ServiceToSwallowGetProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SwallowChannelToServiceProduct
}

// Status returns HTTPResponse.Status
func (r ServiceToSwallowGetProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ServiceToSwallowGetProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ServiceToSwallowUpsertProductWithResponse request returning *ServiceToSwallowUpsertProductResponse
func (c *ClientWithResponses) ServiceToSwallowUpsertProductWithResponse(ctx context.Context, params *ServiceToSwallowUpsertProductParams, reqEditors ...RequestEditorFn) (*ServiceToSwallowUpsertProductResponse, error) {
	rsp, err := c.ServiceToSwallowUpsertProduct(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseServiceToSwallowUpsertProductResponse(rsp)
}

// ServiceToSwallowGetProductWithResponse request returning *ServiceToSwallowGetProductResponse
func (c *ClientWithResponses) ServiceToSwallowGetProductWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*ServiceToSwallowGetProductResponse, error) {
	rsp, err := c.ServiceToSwallowGetProduct(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseServiceToSwallowGetProductResponse(rsp)
}

// ServiceToSwallowGetProductsWithResponse request returning *ServiceToSwallowGetProductsResponse
func (c *ClientWithResponses) ServiceToSwallowGetProductsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ServiceToSwallowGetProductsResponse, error) {
	rsp, err := c.ServiceToSwallowGetProducts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseServiceToSwallowGetProductsResponse(rsp)
}

// ParseServiceToSwallowUpsertProductResponse parses an HTTP response from a ServiceToSwallowUpsertProductWithResponse call
func ParseServiceToSwallowUpsertProductResponse(rsp *http.Response) (*ServiceToSwallowUpsertProductResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ServiceToSwallowUpsertProductResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SwallowChannelToServiceProduct
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseServiceToSwallowGetProductResponse parses an HTTP response from a ServiceToSwallowGetProductWithResponse call
func ParseServiceToSwallowGetProductResponse(rsp *http.Response) (*ServiceToSwallowGetProductResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ServiceToSwallowGetProductResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SwallowChannelToServiceProduct
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseServiceToSwallowGetProductsResponse parses an HTTP response from a ServiceToSwallowGetProductsWithResponse call
func ParseServiceToSwallowGetProductsResponse(rsp *http.Response) (*ServiceToSwallowGetProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ServiceToSwallowGetProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SwallowChannelToServiceProduct
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
