syntax = "proto3";

package swallow_channel_to_service;

import "common/enums.proto";
import "common/i18n.proto";
import "common/range.proto";
import "google/protobuf/timestamp.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
option go_package = "github.com/becash/apis/gen_go/swallow_channel_to_service";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Swallow Service API Channel, Direction from External source ( is client ) to US service ( server )";
    version: "0.1";
    description: "HTTP/JSON API for Swallow service";
  };
  schemes: HTTP;
  consumes: "application/json";
  produces: "application/json";
};

message ProductAvailabilitiesRequest {
  int32 product_id = 1;
  common.DateRange range = 2;
}

message Availability {
  int32 product_id = 1;
  google.protobuf.Timestamp date_time = 2;
  common.Currency currency = 3;
}

message Availabilities {
  Availability data = 1;
  int64 count = 2;
}

message Products {
  repeated Product data = 1;
  int64 count = 2;
}

message ProductsRequest {
  common.Suppliers supplier_id = 1;
}



message Product {
  int32 id = 1;
  common.Suppliers supplier_id =2;
  common.I18n title = 3;
  common.I18n description = 4;
  common.ProductType type = 5;
}


message CreateOrderProduct {
  // shallow product id
  int32 id = 1;
  // This filed  need  to fill in case where product in order  is a service, in this case we book service
  CreateOrderProductBooking booking =2;
}

message CreateOrderProductBooking {
  // external service field
  string booking_reference =1;

}



message CreateOrderRequest {
  common.Currency currency = 1;
  // products  that need  to ad in order when create
  repeated CreateOrderProduct products = 2;
  common.OrderStatus status = 3;
}

message UpdateOrderRequest {
  int32 id = 1;
  common.Currency currency = 3;
}


message Order {
  int32 id = 1;
  google.protobuf.Timestamp created =2;
  common.Currency currency = 3;
  common.OrderStatus status = 4;
}

message Orders {
  repeated Order data = 1;
  int64 count = 2;
}

message OrdersRequest {
  common.DateRange range = 2;
}
